### ISSUE TITLE
Add script to pull demo app examples into example page

### ISSUE THREAD

**Issue by cammace** [mapbox/android-docs#1]

**Comment by zugaldia** [comment]
Now that Batfish has landed and we have a stable documentation system 🎉 I'd like to revisit this ticket. Basically, we want to be able to automatically extract examples from an app (Demo App, Test App) and include them in the docs page:

1. It doesn't need to be the full file, it could be just be relevant portions.
1. It could be integrated with the regular text flow, it wouldn't need to be a page just dedicated for code.

This makes code samples easier to maintain.

Something like what [you can see here](https://cloud.google.com/appengine/docs/standard/java/issue-requests#issuing_an_http_request). The code [comes from this repo](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/appengine/urlfetch/src/main/java/com/example/appengine/UrlFetchServlet.java#L38-L48) where is tagged for easy extraction.

@davidtheclark @cammace What would be the best way to do this while playing nicely with Bastfish?

Related tickets: https://github.com/mapbox/android-docs/issues/5 https://github.com/mapbox/android-docs/issues/180. Also linking https://github.com/kategory/ank that @Guardiola31337 is experimenting with and could help us here.

**Comment by davidtheclark** [comment]
@cammace @zugaldia I recently spoke with @captainbarbosa and the @mapbox/ios team about their team's same desire — to test the source code of their documentation snippets in an environment suitable for that kind of testing.

(@zugaldia that example from Google docs is a great illustration!)

Since @captainbarbosa wants to start experimenting with this for the iOS documentation soon, maybe that project could serve as the proof-of-concept for such a system. Once it works, we could apply the same to Android.

Here's a brief outline of the plan, as I understand it (@captainbarbosa correct please if I'm wrong):

- Establish a nice source repo where the code can live and be tested.
- Use special comments to define lines of code that should be copy-pasted into the documentation repo. Each comment will need to include an id pointing to a corresponding place in the documentation repo where the code should be pasted.
- In the documentation repo, add comments or some other special indicator defining places where code should be pasted. These spots need to bear an id corresponding to those in the source repo comments.
- Write an npm package that performs the copy-pasting. It will use regular expressions to grab snippets from the source repo, then create a pull request updating the documentation repo with any snippets that have changed. (This package would be used in iOS and Android projects, and whoever else has the same need.)

**Comment by 1ec5** [comment]
> Use special comments to define lines of code that should be copy-pasted into the documentation repo. Each comment will need to include an id pointing to a corresponding place in the documentation repo where the code should be pasted.
> In the documentation repo, add comments or some other special indicator defining places where code should be pasted. These spots need to bear an id corresponding to those in the source repo comments.

For reference, the iOS and macOS SDKs currently have a system in place to insert unit test code into guides and generated API references. This is the system we’d like to move into a separate repository that would be more appropriate for /help content. The specific markers we use were inspired by the comment syntax used by Swift playground authors to format explanatory content.

Rather than explain how it works here, I’d encourage you to read the instructions for [adding a new code snippet to header documentation](https://github.com/mapbox/mapbox-gl-native/blob/b0c03f9396f52264184f9a0b18efdf89e787799d/platform/darwin/test/MGLDocumentationExampleTests.swift#L10-L25) and [adding a new code snippet to a Markdown guide](https://github.com/mapbox/mapbox-gl-native/blob/b0c03f9396f52264184f9a0b18efdf89e787799d/platform/darwin/test/MGLDocumentationGuideTests.swift#L10-L27). The [actual insertion script](https://github.com/mapbox/mapbox-gl-native/blob/b0c03f9396f52264184f9a0b18efdf89e787799d/platform/darwin/scripts/update-examples.js) relies on SourceKit for accurately finding the insertion markers in Swift code.

**Comment by zugaldia** [comment]
> Since @captainbarbosa wants to start experimenting with this for the iOS documentation soon, maybe that project could serve as the proof-of-concept for such a system. Once it works, we could apply the same to Android.

👍 Sounds like a plan. Keep us posted on anything we could help with.

**Comment by langsmith** [comment]
transfuser is set up ( 🙇 @colleenmcginnis ) and code can be pulled from demo app examples 🎊 🍾
