### ISSUE TITLE
Feedback for /android/maps/examples/show-a-users-location/

### ISSUE THREAD

**Issue by colleenmcginnis** [mapbox/android-docs#1005]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/android/maps/examples/show-a-users-location/](https://docs.mapbox.com/android/maps/examples/show-a-users-location/)
* Section: maps
* Date received: 2019-07-16T06:20:18.835Z
* Was this page helpful?: 😊

Feedback:
> It is hard to read which part is responsible for reading the location and processing it

cc @langsmith -- maybe code comments would help?

**Comment by langsmith** [comment]
For https://docs.mapbox.com/android/maps/examples/show-a-users-location/, `reading the location and processing it` is happening in https://www.mapbox.com/android-docs/core and behind the scenes in the Maps SDK's `LocationComponent`. The example is a minimalist example of how to display the Maps SDK's `LocationComponent`.

https://docs.mapbox.com/android/maps/examples/location-change-listening/ shows more of the nuts and bolts by showing `onSuccess()`.

Closing because I believe this is unactionable
