### ISSUE TITLE
Direction vs Matrix API contradiction?

### ISSUE THREAD

**Issue by tsuz** [mapbox/android-docs#1134]
Hi,

In the Android SDK documentation's [Direction docs](https://docs.mapbox.com/android/java/overview/directions/), it says "Conversely, the Matrix API does not provide directions routes and distances, which the Directions API does provide." However, in [Matrix docs](https://docs.mapbox.com/android/java/overview/directions-matrix/), it says that it does provide distances. Am I missing something?

CC: @mapbox/android

Thanks,

Taku

**Comment by danswick** [comment]
Thanks for the issue, @tsuz! I think the language in the first link is from a time when the Matrix API did not provide distances. However, that feature has since been added, so we should update the docs! 

Would you like to try opening a pull request with a suggested change? The file that needs to change is here: https://github.com/mapbox/android-docs/blob/publisher-production/src/pages/java/overview/directions.md. 

Happy to help walk through this with you if you want!

**Comment by tsuz** [comment]
@danswick In the contributing guide, it says to create a branch off of `mb-pages`, but I do not see that branch here. Which branch should I work off of?

**Comment by langsmith** [comment]
@tsuz  you can branch off of `publisher-production` and then eventually open a pull request. I will create a separate pr to update the contributing guide.

**Comment by tsuz** [comment]
I've created a PR here. Can you please take a look? @langsmith @danswick 
https://github.com/mapbox/android-docs/pull/1136

**Comment by tsuz** [comment]
Closing as this is merged
