### ISSUE TITLE
Should current map-sdk/tutorials be map-sdk/tutorials/first-steps?

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/android-docs#154]
If the intention is to add more tutorials in the future, I think we may need to qualify the URL: `map-sdk/tutorials` -> `map-sdk/tutorials/first-steps`. (Then we could add, for example, `map-sdk/tutorials/summoning-turtles`.)

This would require us to write a 301 redirect in Fastly. 

@cammace: What do you think? Am I right in suspecting it would need to be changed as soon as we write the next tutorial, or am I misunderstanding.

**Comment by cammace** [comment]
I imagine we will eventually be creating some sort of landing page for the tutorial section in the future, otherwise, the intention here was to have the first-steps guide always be the landing page. We do the same for all the getting-started pages, that is, instead of the URL being `android-docs/map-sdk/overview/getting-started` the URL is `android-docs/map-sdk/overview/`. 

That being said, I think it's best to use the URL that makes most sense, it's your call @davidtheclark

**Comment by davidtheclark** [comment]
> We do the same for all the getting-started pages

@cammace: I see. Thanks for explaining. It's fine this way — I just wanted to avoid having to do a 301 redirect soon.
