### ISSUE TITLE
The color green

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/android-docs#181]
I just want to sort out the issue with the color green.

Because the whole color scheme in the docs was slightly off from [the brand colors](https://www.mapbox.com/styleguide/colors/), I had assumed the lighter green was just another stylistic variation, and @katmeng and I thought we should probably use the brand green instead.

@cammace informed me that that the lighter green was chosen for a special reason, though: because it's the Android green. He and @zugaldia like it for that reason.

Another problem I just realized with the Android green is that using it as a background behind white text fails both AAA and AA accessibility checks for contrast: http://webaim.org/resources/contrastchecker/?fcolor=fff&bcolor=8cca44.

So @katmeng, what do you think we should do? Do you think the Androidiness of the lighter green is worth the non-brandiness of it? Which should we go with?

cc @emilyville

**Comment by katmeng** [comment]
Thank you @davidtheclark for sorting out this issue 🙏 

We should replace the Android green with our own brand green because a) the docs is a Mapbox owned page and b) I'm unsure why we'd want to brand out page just for Android. Android is mentioned in the Platform drop down and in the URL so I'm sure people will be aware that they're on the Android page. 

Also, thanks for testing out the AAA and AA accessibility because that's another reason for why we should use our brand green. 

Also, our brand green is a nice color!

**Comment by davidtheclark** [comment]
Haha, it's also worth noting that the brand green fails the accessibility check: http://webaim.org/resources/contrastchecker/?fcolor=fff&bcolor=33c377

I didn't check that before! I imagine the lighter green fails *harder*, but those no distinction here: both fail.
