### ISSUE TITLE
Add bottom document component

### ISSUE THREAD

**Issue by cammace** [mapbox/android-docs#90]
Adding a bottom component to the docs will allow us to put UI for rating the document, pointing out that users can edit these docs, and even possibly push the demo app.

<img width="138" alt="screen shot 2017-06-06 at 11 09 16 pm" src="https://user-images.githubusercontent.com/5652865/26860685-3e806fd6-4b0d-11e7-8eb9-64b9a91fe401.png">

@mayagao Do you think you could come up with something? It currently looks like this:

<img width="859" alt="screen shot 2017-06-06 at 11 11 37 pm" src="https://user-images.githubusercontent.com/5652865/26860730-8b2c49c2-4b0d-11e7-83c3-6c076f0645bf.png">

**Comment by langsmith** [comment]
Closing as this is a higher level docs decision made by @mapbox/docs . @colleenmcginnis is looking into a component like this. A feedback component like this would be added to all docs pages rather than just the android docs. This functionality doesn't need to be tracked by a single ticket in this particular repo.
